version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"  # Web management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  rabbitmq_data:
#   mysql_data:
#   mongodb_data:
#   nsqlookupd_data:
#   nsqd_data:
#   postgres_data: